### ISSUE TITLE
403 error forbidden when download the efficientnet weights for training

### ISSUE THREAD

**Issue by lchunleo** [signatrix/efficientdet#21]
Hi  
Thanks for sharing your code. i had tried to perform train but it hit a forbidden error when it trying to download the efficientNet weights. i have already login into the gCloud with authenticate  

Can you advise? thanks

 File "/home/hello/efficientdet/effdev/lib/python3.6/site-packages/efficientnet_pytorch/utils.py", line 310, in load_pretrained_weights
    state_dict = model_zoo.load_url(url_map[model_name])
  File "/home/hello/efficientdet/effdev/lib/python3.6/site-packages/torch/hub.py", line 492, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/hello/efficientdet/effdev/lib/python3.6/site-packages/torch/hub.py", line 391, in download_url_to_file
    u = urlopen(url)
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by uvipen** [comment]
Hi,
We didnt experience this issue. Did you try to update your pytorch?

**Comment by lchunleo** [comment]
the error seem to comes from permission denied to download the weights...
Downloading: "http://storage.googleapis.com/public-models/efficientnet/efficientnet-b0-355c32eb.pth" 

Secondly, if is possible to bypass the downloading of the weights and instead used already downloaded weights?

my torch is 1.4

**Comment by jGsch** [comment]
@lchunleo 

Upgrade your efficientnet package with `pip install --upgrade efficientnet-pytorch`.

From https://github.com/lukemelas/EfficientNet-PyTorch:

> IMPORTANT NOTE: In the latest update, I switched hosting providers for the pretrained models, as the previous models were becoming extremely expensive to host. This will break old versions of the library. I apologize, but I cannot afford to keep serving the models on the old provider. Everything should work properly if you update the library:

**Comment by lchunleo** [comment]
@jGsch 
Thanks. had tried it but it does not work. Does it work for you ? If yes, do you install any google cloud authentication stuff? thanks

**Comment by jGsch** [comment]
@lchunleo 

> had tried it but it does not work.

I think the package hasn't been properly updated. If you look at the [commit](https://github.com/lukemelas/EfficientNet-PyTorch/commit/396b06bc1489a21317ef81ac530274fe64cddc68#diff-57e79865f7111e0dd0165032e805d446), the host is no longer google (as indicated on your error) but windows.

> Secondly, if is possible to bypass the downloading of the weights and instead used already downloaded weights?

[Here](https://github.com/signatrix/efficientdet/blob/master/src/model.py#L178), replace 
```
model = EffNet.from_pretrained('efficientnet-b0')
```
by 
```
model = EffNet.from_name('efficientnet-b0')
model.load_state_dict(<your-state-dict>)
```

**Comment by lchunleo** [comment]
> @lchunleo
> 
> > had tried it but it does not work.
> 
> I think the package hasn't been properly updated. If you look at this [commit](https://github.com/lukemelas/EfficientNet-PyTorch/commit/396b06bc1489a21317ef81ac530274fe64cddc68#diff-57e79865f7111e0dd0165032e805d446), the host is no longer google (as indicated on your error) but windows.
> 
> > Secondly, if is possible to bypass the downloading of the weights and instead used already downloaded weights?
> 
> [Here](https://github.com/signatrix/efficientdet/blob/master/src/model.py#L178), replace
> 
> ```
> model = EffNet.from_pretrained('efficientnet-b0')
> ```
> 
> by
> 
> ```
> model = EffNet.from_name('efficientnet-b0')
> model.load_state_dict(<your-state-dict>)
> ```

@jGsch Thank you. your solution works!
