### ISSUE TITLE
Training with images of different sizes

### ISSUE THREAD

**Issue by chinglamchoi** [signatrix/efficientdet#38]
Hello! I have a dataset of images of different sizes, how do you recommend I perform training with efficientdet? I understand that efficientnet relies on compound scaling and thus cannot be size-invariant unlike darknet. Would would you recommend padding to 512x512x3? Thanks.

**Comment by CraigWang1** [comment]
By my understanding, the code already resizes it so that one side is 512 pixels long (while still preserving true shapes, no distortion), so you shouldn't have to worry about that.

Hope this helps, but please correct me if I'm wrong!

**Comment by chinglamchoi** [comment]
Oh it works great! Saves me the work :) Absolutely helps. Thank you for this project!

**Comment by CraigWang1** [comment]
No problem happy to help!
