### ISSUE TITLE
Can't get 31.4 model by trainning

### ISSUE THREAD

**Issue by lampsonSong** [signatrix/efficientdet#42]
Thanks for the great work firstly. 

I run the code successfully, and train the model with coco2017, but the best model I trained can just reach 22% in coco2017 val set. I have tried lr with 1e-4, 1e-5 and 5e-6. Compared with the author's code, I use batch_size = 14 and four TITAN cards. Are there any tips or warnings when training?

**Comment by zylo117** [comment]
same here
