### ISSUE TITLE
You're one of the best people I've ever seen, and you did a really good job in Efficientdet, thank you.The greatest author in the universe, you must grant my request

### ISSUE THREAD

**Issue by 944284742** [signatrix/efficientdet#7]
The best author in the world, can I trouble you with something?Can you give us the training and evaluation methods of voc?Because coco many functions are encapsulated, such as calculating mAP and so on.With voc based training and evaluation, we were able to quickly modify our own data as we trained it.

**Comment by heartInsert** [comment]
Nope  ,friend  ,I   think  cocoapi  is  not   so  difficult to  understand  ,  you  must   read  it  step  by  step   if  you  want  to   study   objectDetection .
